services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trello-api
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5848:5848"
    environment:
      - APP_PORT=5848
      - NODE_ENV=development
      - DATABASE_URL=mysql://root@db:3306/trello_dbs
    depends_on:
      - db
  db:
    image: mariadb
    container_name: trello-db
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=trello_dbs
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: